/* eslint-env mocha */
const Graph = require('../../../graph')
const layout = require('../../../layouter/sugiyama-compound/position-assignment')

describe('orderLayers', () => {
  it('', () => {
    const [a, b, c, g, h, i, j, k, v] = 'abcghijkv'
    const graph = new Graph()
      .addVertex(a, {layer: [0, 0], order: 0})
      .addVertex(b, {layer: [0, 0], order: 2})
      .addVertex(c, {layer: [0, 0], order: 1})
      .addVertex(g, {layer: [0, 1], order: 3})
      .addVertex(h, {layer: [0, 1], order: 1})
      .addVertex(i, {layer: [0, 1], order: 0})
      .addVertex(j, {layer: [0, 1], order: 4})
      .addVertex(k, {layer: [0, 1], order: 3})
      .addVertex(v, {layer: [0], order: 0})
      .addEdge(a, c)
      .addEdge(a, i)
      .addEdge(b, c)
      .addEdge(b, j)
      .addEdge(b, k)
      .addEdge(c, g)
      .addEdge(g, i)
      .addEdge(g, j)
      .addEdge(g, k)
      .addEdge(h, k)
      .setChild(v, a)
      .setChild(v, b)
      .setChild(v, c)
      .setChild(v, g)
      .setChild(v, h)
      .setChild(v, i)
      .setChild(v, j)
      .setChild(v, k)
    layout(graph)
    console.log(graph)
  })
})
