/* eslint-env mocha */
const Graph = require('../../../graph')
const orderLayers = require('../../../layouter/sugiyama-compound/crossing-reduction')

describe('orderLayers', () => {
  it('', () => {
    const [a, b, c, g, h, i, j, k, v] = 'abcghijkv'
    const graph = new Graph()
      .addVertex(a, {layer: [0, 0]})
      .addVertex(b, {layer: [0, 0]})
      .addVertex(c, {layer: [0, 0]})
      .addVertex(g, {layer: [0, 1]})
      .addVertex(h, {layer: [0, 1]})
      .addVertex(i, {layer: [0, 1]})
      .addVertex(j, {layer: [0, 1]})
      .addVertex(k, {layer: [0, 1]})
      .addVertex(v, {layer: [0]})
      .addEdge(a, c)
      .addEdge(a, i)
      .addEdge(b, c)
      .addEdge(b, j)
      .addEdge(b, k)
      .addEdge(c, g)
      .addEdge(g, i)
      .addEdge(g, j)
      .addEdge(g, k)
      .addEdge(h, k)
      .setChild(v, a)
      .setChild(v, b)
      .setChild(v, c)
      .setChild(v, g)
      .setChild(v, h)
      .setChild(v, i)
      .setChild(v, j)
      .setChild(v, k)
    orderLayers(graph, 1)
  })

  it('works', () => {
    const [a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v] = 'abcdefghijklmnopqrstuv'
    const graph = new Graph()
      .addVertex(a, {layer: [0]})
      .addVertex(b, {layer: [0, 0]})
      .addVertex(c, {layer: [0, 1]})
      .addVertex(d, {layer: [0, 0, 0]})
      .addVertex(e, {layer: [0, 0, 1]})
      .addVertex(f, {layer: [0, 0, 1]})
      .addVertex(g, {layer: [0, 1, 1]})
      .addVertex(h, {layer: [0, 1, 0]})
      .addVertex(i, {layer: [0, 1, 2]})
      .addVertex(j, {layer: [0, 0, 1, 0]})
      .addVertex(k, {layer: [0, 0, 1, 0]})
      .addVertex(l, {layer: [0, 0, 1, 1]})
      .addVertex(m, {layer: [0, 1, 1, 1]})
      .addVertex(n, {layer: [0, 1, 1, 2]})
      .addVertex(o, {layer: [0, 1]})
      .addVertex(p, {layer: [0, 1, 0]})
      .addVertex(q, {layer: [0, 1, 1]})
      .addVertex(r, {layer: [0, 1, 1, 0]})
      .addVertex(s, {layer: [0, 1, 1, 3]})
      .addVertex(t, {layer: [0, 1, 1]})
      .addVertex(u, {layer: [0, 1, 1, 2]})
      .addVertex(v, {layer: [0, 1, 1]})
      .addEdge(b, c)
      .addEdge(b, o)
      .addEdge(d, e)
      .addEdge(h, q)
      .addEdge(j, l)
      .addEdge(k, l)
      .addEdge(m, n)
      .addEdge(m, u)
      .addEdge(n, s)
      .addEdge(p, g)
      .addEdge(r, m)
      .addEdge(t, i)
      .addEdge(v, i)
      .setChild(a, b)
      .setChild(a, c)
      .setChild(a, o)
      .setChild(b, d)
      .setChild(b, e)
      .setChild(b, f)
      .setChild(c, g)
      .setChild(c, h)
      .setChild(c, i)
      .setChild(c, q)
      .setChild(c, t)
      .setChild(c, v)
      .setChild(e, j)
      .setChild(f, k)
      .setChild(f, l)
      .setChild(g, m)
      .setChild(g, n)
      .setChild(o, p)
      .setChild(q, r)
      .setChild(t, s)
      .setChild(v, u)
    orderLayers(graph, 1)
  })
})
